<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OrderManagement.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OrderManagement.Infrastructure" />
    <InternalsVisibleTo Include="OrderManagement.Infrastructure.Tests" />
  </ItemGroup>

</Project>
